
STATUS_NOTICIA_CRIADA = 1
STATUS_NOTICIA_PUBLICADA = 2
STATUS_NOTICIA_ARQUIVADA = 3

STATUS_NOTICIA_CHOICES = (
  (STATUS_NOTICIA_CRIADA, 'Criada'),
  (STATUS_NOTICIA_PUBLICADA, 'Publicada'),
  (STATUS_NOTICIA_ARQUIVADA, 'Arquivada'),
)