# Generated by Django 3.2.7 on 2022-08-19 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalhador',
            name='faixas',
        ),
        migrations.RemoveField(
            model_name='trabalhador',
            name='tipo_mediunidade',
        ),
    ]
