# Generated by Django 3.2.7 on 2021-10-08 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('data_nascimento', models.DateField(verbose_name='Data de nascimento')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Telefone')),
                ('telefone_whatsapp', models.BooleanField(default=False, verbose_name='Telefone é Whatsapp')),
                ('doencas_preexistentes', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Tem doença(s) diagnosticada(s) por médico(s)?')),
                ('descricao_doencas_preexistentes', models.TextField(blank=True, null=True, verbose_name='Quais?')),
                ('possui_marcapasso', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='É portador de marcapasso?')),
                ('toma_medicacao', models.IntegerField(choices=[(0, 'Não'), (1, 'Sim')], default=0, verbose_name='Está tomando medicação?')),
                ('descricao_medicacao', models.TextField(blank=True, null=True, verbose_name='Quais?')),
                ('motivo_atendimento', models.TextField(blank=True, null=True, verbose_name='Motivo da procura pelo atendimento (o que procura obter?)')),
            ],
            options={
                'verbose_name': 'Consulente',
                'verbose_name_plural': 'Consulentes',
            },
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_retorno', models.BooleanField(default=False, verbose_name='Precisa de retorno')),
                ('data', models.DateField(verbose_name='Data')),
                ('recomendacoes', models.TextField(blank=True, null=True, verbose_name='Recomendações')),
                ('consulente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_consulente', to='atendimento.consulente', verbose_name='Consulente')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
            },
        ),
    ]
