# Generated by Django 3.2.7 on 2021-10-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0001_initial'),
        ('cadastros_basicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultaPretosVelhos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_retorno', models.BooleanField(default=False, verbose_name='Precisa de retorno')),
                ('data', models.DateField(verbose_name='Data')),
                ('recomendacoes', models.TextField(blank=True, null=True, verbose_name='Recomendações')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('consulente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultapretosvelhos_consulente', to='usuario.consulente', verbose_name='Consulente')),
                ('entidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consultapretosvelhos_entidade', to='cadastros_basicos.entidade', verbose_name='Entidade')),
                ('terapias_recomendadas', models.ManyToManyField(related_name='consultapretosvelhos_terapias', to='cadastros_basicos.Terapia', verbose_name='Terapias recomendadas')),
                ('trabalhadores', models.ManyToManyField(related_name='consultapretosvelhos_trabalhadores', to='usuario.Trabalhador', verbose_name='Trabalhadores')),
            ],
            options={
                'verbose_name': 'Consulta Preto Velho',
                'verbose_name_plural': 'Consulta Pretos Velhos',
            },
        ),
        migrations.CreateModel(
            name='AgendaLibertacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('consulentes', models.ManyToManyField(related_name='agendalibertacao_consulentes', to='usuario.Consulente', verbose_name='Consulentes')),
            ],
            options={
                'verbose_name': 'Agenda libertação',
                'verbose_name_plural': 'Agenda libertação',
            },
        ),
    ]
