# Generated by Django 3.2.7 on 2022-08-19 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20220818_2228'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros_basicos', '0002_auto_20220818_2228'),
        ('atendimento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'ordering': ['-data'], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
        migrations.AddField(
            model_name='atendimento',
            name='guia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_guia', to='cadastros_basicos.entidade', verbose_name='Guia'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='mediador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_mediador', to='usuario.trabalhador', verbose_name='Mediador'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimento_medium', to='usuario.trabalhador', verbose_name='Médium'),
        ),
        migrations.AddField(
            model_name='consulente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AlterField(
            model_name='consulente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
