# Generated by Django 3.2.7 on 2021-10-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='funcao',
            field=models.ManyToManyField(blank=True, related_name='trabalhador_funcao', to='contrib.TrabalhadorFuncao', verbose_name='Funções'),
        ),
        migrations.AlterField(
            model_name='trabalhador',
            name='tipo_mediunidade',
            field=models.ManyToManyField(blank=True, related_name='trabalhador_tipo_mediunidade', to='contrib.TipoMediunidade', verbose_name='Tipos de mediunidade'),
        ),
    ]
