# Generated by Django 3.2.7 on 2021-10-02 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
