# Generated by Django 3.2.7 on 2021-10-03 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrib', '0003_auto_20211002_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AddField(
            model_name='trabalhador',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
